version: "3"

services:
  eventsbot:
    image: hackgvl/eventsbot
    container_name: eventsbot
    restart: always
    environment:
      - BOT_TOKEN=bot_token_here
      - SIGNING_SECRET=signing_secret_here
      - PORT=3000
      - TZ=US/Eastern
    volumes:
      - ./eventsbot.db:/usr/src/app/eventsbot.db
    ports:
      - 127.0.0.1:3000:3000
