version: "3"

services:
  slack-events-bot:
    image: hackgvl/slack-events-bot
    container_name: slack-events-bot
    restart: always
    environment:
      - BOT_TOKEN=bot_token_here
      - SIGNING_SECRET=signing_secret_here
      - PORT=3000
      - TZ=US/Eastern
    volumes:
      - ./slack-events-bot.db:/usr/src/app/slack-events-bot.db
    ports:
      - 127.0.0.1:3000:3000
