version: "3"

services:
  c4g-events:
    image: codeforgreenville/c4g-events
    container_name: c4g-events
    restart: always
    environment:
      - BOT_TOKEN=bot_token_here
      - SIGNING_SECRET=signing_secret_here
      - PORT=3000
      - TZ=US/Eastern
    volumes:
      - ./c4g.db:/usr/src/app/c4g.db
